In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
array = genfromtxt('../DATA/bank_note_data.txt', delimiter=',') # delimiter is used to separate each keyword in array

In [3]:
array

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
array

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
labels = array[:,4]
features = array[:,0:4]
print(labels, end="\n\n\n")
print(features)

[0. 0. 0. ... 1. 1. 1.]


[[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]


In [6]:
X = features
y = labels

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [9]:
len(X_train)

919

In [10]:
len(X_test)

453

In [11]:
from sklearn.preprocessing import MinMaxScaler # this finds min and max of the given set. Makes CNN to learn better and easier

In [12]:
scaler_object = MinMaxScaler()

In [13]:
scaler_object.fit(X_train)

scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [21]:
print(scaled_X_train.max())
print(scaled_X_train.min())

1.0000000000000002
0.0


In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [17]:
model = Sequential() # this is your model

model.add(Dense(4, input_dim=4, activation = 'relu')) # Add densely connected layer, 4 is a num of feature
                                                      # We have 4 neurons in that unit
    
model.add(Dense(8, activation = 'relu')) # No input_dim is given. Hidden layer.

model.add(Dense(1,  activation = 'sigmoid')) # We want single output at the end


In [18]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [19]:
model.fit(scaled_X_train, y_train, epochs = 50, verbose = 2)

Epoch 1/50
29/29 - 0s - loss: 0.7617 - accuracy: 0.4505
Epoch 2/50
29/29 - 0s - loss: 0.7246 - accuracy: 0.4353
Epoch 3/50
29/29 - 0s - loss: 0.6999 - accuracy: 0.3373
Epoch 4/50
29/29 - 0s - loss: 0.6801 - accuracy: 0.6366
Epoch 5/50
29/29 - 0s - loss: 0.6595 - accuracy: 0.6670
Epoch 6/50
29/29 - 0s - loss: 0.6350 - accuracy: 0.7160
Epoch 7/50
29/29 - 0s - loss: 0.6141 - accuracy: 0.7269
Epoch 8/50
29/29 - 0s - loss: 0.5929 - accuracy: 0.7541
Epoch 9/50
29/29 - 0s - loss: 0.5716 - accuracy: 0.7584
Epoch 10/50
29/29 - 0s - loss: 0.5527 - accuracy: 0.7748
Epoch 11/50
29/29 - 0s - loss: 0.5341 - accuracy: 0.7813
Epoch 12/50
29/29 - 0s - loss: 0.5158 - accuracy: 0.7867
Epoch 13/50
29/29 - 0s - loss: 0.4985 - accuracy: 0.7998
Epoch 14/50
29/29 - 0s - loss: 0.4816 - accuracy: 0.8150
Epoch 15/50
29/29 - 0s - loss: 0.4667 - accuracy: 0.8194
Epoch 16/50
29/29 - 0s - loss: 0.4504 - accuracy: 0.8303
Epoch 17/50
29/29 - 0s - loss: 0.4354 - accuracy: 0.8477
Epoch 18/50
29/29 - 0s - loss: 0.4207 - 

In [22]:
from sklearn.metrics import confusion_matrix, classification_report

In [25]:
model.metrics_names

['loss', 'accuracy']

In [26]:
predictions = model.predict_classes(scaled_X_test)

C:\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [27]:
confusion_matrix(y_test, predictions)

array([[253,   4],
       [ 11, 185]], dtype=int64)

In [28]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.96      0.98      0.97       257
         1.0       0.98      0.94      0.96       196

    accuracy                           0.97       453
   macro avg       0.97      0.96      0.97       453
weighted avg       0.97      0.97      0.97       453



In [29]:
model.save('myfirstmodel.h5')

In [30]:
from keras.models import load_model

In [31]:
nmodel = load_model('myfirstmodel.h5')

In [32]:
nmodel.predict_classes(X_test)

C:\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    